### ISSUE TITLE
안녕하세요 번역 관련 방법 문의 드립니다.

### ISSUE THREAD

**Issue by devFallingstar** [wb1016/sb_korpatch#1]
안녕하세요. 스타바운드 플레이어입니다.

github 통해서 번역에 참가하려 하는데 번역 방법에 대한 안내를 확인할 수 있는 곳이 있을까요?

**Comment by wb1016** [comment]
작은 규모의 기여는 pull request 하시면 되구요, 지속적으로 참여하고 싶으시다면 https://discord.gg/AH5z9Ky 여기 디스코드 서버에 들어와주세요
