### ISSUE TITLE
달 천체정보 로딩 실패 및 UI 프리징

### ISSUE THREAD

**Issue by wb1016** [wb1016/sb_korpatch#16]
달에 좌클릭을 해서 천체 정보를 보려고 하면 그대로 칵핏 UI가 얼어버립니다. esc로 내린 후 좌클릭 없이 우클릭만으로 이동하면 이동은 할 수 있습니다. *.patch 파일에 있는 string 정보를 읽어오지 못합니다.

stacktrace를 포함한 로그 파일입니다.
[cockpit-moon-bug-log.txt](https://github.com/wb1016/sb_korpatch/files/5703954/cockpit-moon-bug-log.txt)

**Comment by OABHs** [comment]
https://gall.dcinside.com/mgallery/board/view/?id=starbound&no=1899&page=1
한 분이 해결법을 올리신 것 같습니다.

**Comment by wb1016** [comment]
syntax error일거라고 생각은 했지만 두 영역의 포맷이 다를거라고는 생각도 못했네요...
