### ISSUE TITLE
'Ancient'의 번역명

### ISSUE THREAD

**Issue by wb1016** [wb1016/sb_korpatch#5]
게임 속 고대 종족인 'Ancient'의 번역명이 아직 정해지지 않았습니다.

**Comment by OABHs** [comment]
예전에 투표했다시피 '고대인'이 어떨까 합니다.

**Comment by SurrealView** [comment]
저도 고대인이 무난한 거 같네요
누군가 선조라는 단어를 제시한적도 있긴 해요

**Comment by wb1016** [comment]
discussion으로 이동.
